// frontend/src/lib/utils/pdfExport.ts
// Purpose: Generate professional PDF from optimizer results — client-side, no backend needed
// NOT for: CSV exports (that's csvParser.ts)

import { jsPDF } from 'jspdf'
import type { OptimizerResponse } from '../types'

// WHY: Strip HTML tags from description for clean PDF text
function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').trim()
}

export function downloadPDF(response: OptimizerResponse): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 15
  const contentWidth = pageWidth - margin * 2
  let y = 20

  // WHY: Check remaining space and add page if needed
  const checkPage = (needed: number) => {
    if (y + needed > 275) {
      doc.addPage()
      y = 20
    }
  }

  // Header
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('OctoHelper — Listing Optimizer', margin, y)
  y += 8

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(120)
  const meta = [
    `Marketplace: ${response.marketplace}`,
    `Brand: ${response.brand}`,
    `Mode: ${response.mode}`,
    `Date: ${new Date().toLocaleDateString('pl-PL')}`,
  ].join('  |  ')
  doc.text(meta, margin, y)
  y += 4

  // Divider
  doc.setDrawColor(200)
  doc.line(margin, y, pageWidth - margin, y)
  y += 8
  doc.setTextColor(0)

  // Scores summary
  const scores = response.scores
  if (scores) {
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Scores', margin, y)
    y += 6
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    const scoreLines = [
      `Keyword Coverage: ${scores.coverage_pct}% (${scores.coverage_mode})`,
      `Title Coverage: ${scores.title_coverage_pct}%`,
      `Backend Utilization: ${scores.backend_utilization_pct}% (${scores.backend_byte_size}/249 bytes)`,
      `Compliance: ${scores.compliance_status}`,
    ]
    scoreLines.forEach(line => {
      doc.text(line, margin, y)
      y += 5
    })
    y += 4
  }

  // Ranking Juice
  if (response.ranking_juice) {
    checkPage(20)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(`Ranking Juice: ${response.ranking_juice.score}/100 (${response.ranking_juice.grade})`, margin, y)
    y += 6
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text(response.ranking_juice.verdict, margin, y, { maxWidth: contentWidth })
    y += 8
  }

  // Title
  checkPage(20)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Title', margin, y)
  y += 6
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const titleLines = doc.splitTextToSize(response.listing.title, contentWidth)
  doc.text(titleLines, margin, y)
  y += titleLines.length * 5 + 4

  doc.setFontSize(8)
  doc.setTextColor(120)
  doc.text(`${response.listing.title.length} characters`, margin, y)
  y += 8
  doc.setTextColor(0)

  // Bullet Points
  checkPage(15)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text(`Bullet Points (${response.listing.bullet_points.length})`, margin, y)
  y += 6
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')

  response.listing.bullet_points.forEach((bullet, i) => {
    checkPage(15)
    const bulletLines = doc.splitTextToSize(`${i + 1}. ${bullet}`, contentWidth - 5)
    doc.text(bulletLines, margin, y)
    y += bulletLines.length * 5 + 3
  })
  y += 4

  // Description
  checkPage(20)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Description', margin, y)
  y += 6
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  const descText = stripHtml(response.listing.description)
  const descLines = doc.splitTextToSize(descText, contentWidth)
  // WHY: Long descriptions may span multiple pages
  descLines.forEach((line: string) => {
    checkPage(6)
    doc.text(line, margin, y)
    y += 4.5
  })
  y += 4

  // Backend Keywords
  if (response.listing.backend_keywords) {
    checkPage(20)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Backend Keywords', margin, y)
    y += 6
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    const bkLines = doc.splitTextToSize(response.listing.backend_keywords, contentWidth)
    doc.text(bkLines, margin, y)
    y += bkLines.length * 4.5 + 2

    const byteSize = new TextEncoder().encode(response.listing.backend_keywords).length
    doc.setFontSize(8)
    doc.setTextColor(120)
    doc.text(`${byteSize}/249 bytes`, margin, y)
    y += 6
    doc.setTextColor(0)
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p)
    doc.setFontSize(7)
    doc.setTextColor(160)
    doc.text(
      `Generated by OctoHelper — panel.octohelper.com — Page ${p}/${pageCount}`,
      pageWidth / 2, 290,
      { align: 'center' }
    )
  }

  const brand = response.brand?.replace(/\s+/g, '_') || 'listing'
  doc.save(`listing_${brand}_${response.marketplace}_${Date.now()}.pdf`)
}
